# Generated by Django 5.2.1 on 2025-06-06 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='author',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='category',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='podcast',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='podcast',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='podcast',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='content',
        ),
        migrations.AddField(
            model_name='media',
            name='podcast_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='podcast_media', to='media.category'),
        ),
        migrations.AddField(
            model_name='media',
            name='podcast_release_date',
            field=models.DateField(blank=True, help_text='Release date for podcast episodes', null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='podcast_season_number',
            field=models.PositiveIntegerField(blank=True, help_text='Season number if part of a podcast series', null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='podcast_series_name',
            field=models.CharField(blank=True, help_text='Name of the podcast series if part of one', max_length=255),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('book', 'Book'), ('manuscript', 'Manuscript'), ('comic', 'Comic'), ('podcast', 'Podcast'), ('other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='content_type',
            field=models.CharField(choices=[('magazine', 'Magazine'), ('media', 'Media')], max_length=10),
        ),
        migrations.DeleteModel(
            name='PodcastCategory',
        ),
        migrations.DeleteModel(
            name='Podcast',
        ),
    ]
