# Generated by Django 5.2.1 on 2025-06-05 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_comment_options_remove_comment_media_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='favorite',
            name='comic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comic_favorites', to='media.comic'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='magazine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='magazine_favorites', to='media.magazine'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_favorites', to='media.media'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='podcast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='podcast_favorites', to='media.podcast'),
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='content',
        ),
    ]
