# Generated by Django 5.2.1 on 2025-06-05 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_alter_favorite_unique_together_favorite_comic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='media',
        ),
    ]
