# Generated by Django 5.2.1 on 2025-06-05 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_rename_content_comment_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='comic',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
